insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("MacBook Pro", "computer", 2399, "Apple", 100, "Power. Moves.")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("MacBook Air", "computer", 999, "Apple", 200, "Light. Speed.")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("iMac", "computer", 2299, "Apple", 150, "Pretty. Freaking powerful.")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("Galaxy Book Fles", "computer", 450, "Samsung", 300, "QLED brilliance in a powerful 2-in-1 PC")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("Odyssey Monitor", "appliance", 1199, "Samsung", 250,  "Wider View. Winning Play")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("French Door Refrigerator", "appliance", 2699, "Samsung", 50, "It’s all on your fridge")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("SmartThings Cam", "appliance", 89, "Samsung", 10, "Full HD camera monitors your home for 24 hours.")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("QLED", "appliance", 9883, "Samsung", 5, "8K display")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("Nike Free Run 5.0", "sundries", 90, "NIKE", 500, "Running Shoes")
insert into productTable(name, category, price, manufacturer, unitInStock, description) values ("nike air zoom pegasus 37", "sundries", 115, "NIKE", 500, "Speed Shoes")